C     This file was automatically generated by ALOHA
C     but has been modified by CAFE

      SUBROUTINE LRV1_0(F1, F2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 VERTEX
      VERTEX = -COUP*((F1(4)*V3(3) - F1(3)*V3(4))*F2(6) - (F1(4)*V3(5) - F1(3)*V3(6))*F2(5))
      END


