C     This file was automatically generated by ALOHA
C     but has been modified by CAFE

      SUBROUTINE VIVLVLVR1P0_2(V1, V3, V4, COUP, M2, W2,V2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M2
      REAL*8 P2(0:3)
      COMPLEX*16 TMP1
      COMPLEX*16 TMP2
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(6)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      REAL*8 W2
      COMPLEX*16 DENOM
      V2(1) = +V1(1)+V3(1)+V4(1)
      V2(2) = +V1(2)+V3(2)+V4(2)
      P2(0) = -DBLE(V2(1))
      P2(1) = -DBLE(V2(2))
      P2(2) = -DIMAG(V2(2))
      P2(3) = -DIMAG(V2(1))
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      TMP1 = V1(3)*V4(6) - V1(4)*V4(5) - V1(5)*V4(4) + V1(6)*V4(3)
      TMP2 = V1(3)*V3(6) - V1(4)*V3(5) - V1(5)*V3(4) + V1(6)*V3(3)
      V2(3) = -DENOM*CI*(TMP1*V3(3) - TMP2*V4(3))/2
      V2(4) = -DENOM*CI*(TMP1*V3(4) - TMP2*V4(4))/2
      V2(5) = -DENOM*CI*(TMP1*V3(5) - TMP2*V4(5))/2
      V2(6) = -DENOM*CI*(TMP1*V3(6) - TMP2*V4(6))/2
      END


