C     This file was automatically generated by ALOHA
C     but has been modified by CAFE

      SUBROUTINE VLVRVRVR4_0(V1, V2, V3, V4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 TMP1
      COMPLEX*16 TMP2
      COMPLEX*16 TMP3
      COMPLEX*16 TMP4
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      COMPLEX*16 VERTEX
      TMP1 = V1(3)*V3(6) - V1(4)*V3(5) - V1(5)*V3(4) + V1(6)*V3(3)
      TMP2 = V2(3)*V4(6) - V2(4)*V4(5) - V2(5)*V4(4) + V2(6)*V4(3)
      TMP3 = V1(3)*V2(6) - V1(4)*V2(5) - V1(5)*V2(4) + V1(6)*V2(3)
      TMP4 = V3(3)*V4(6) - V3(4)*V4(5) - V3(5)*V4(4) + V3(6)*V4(3)
      VERTEX = COUP*CI*(TMP1*TMP2 - TMP3*TMP4)/4
      END


