C     This file was automatically generated by ALOHA
C     but has been modified by CAFE

C     
      SUBROUTINE VRVRVR1P0_2(V1, V3, COUP, M2, W2,V2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M2
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP1
      COMPLEX*16 TMP2
      COMPLEX*16 TMP3
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(6)
      COMPLEX*16 V3(*)
      REAL*8 W2
      COMPLEX*16 DENOM
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P3(0) = DBLE(V3(1))
      P3(1) = DBLE(V3(2))
      P3(2) = DIMAG(V3(2))
      P3(3) = DIMAG(V3(1))
      V2(1) = +V1(1)+V3(1)
      V2(2) = +V1(2)+V3(2)
      P2(0) = -DBLE(V2(1))
      P2(1) = -DBLE(V2(2))
      P2(2) = -DIMAG(V2(2))
      P2(3) = -DIMAG(V2(1))
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      TMP0 = (V3(3)*(P2(0) - P2(3)) - V3(4)*(P2(1) + CI*P2(2)) - V3(5)*(P2(1) - CI*P2(2)) + V3(6)*(P2(0) + P2(3)))
      TMP1 = (V3(3)*(P1(0) - P1(3)) - V3(4)*(P1(1) + CI*P1(2)) - V3(5)*(P1(1) - CI*P1(2)) + V3(6)*(P1(0) + P1(3)))
      TMP2 = (V1(3)*(P3(0) - P3(3)) - V1(4)*(P3(1) + CI*P3(2)) - V1(5)*(P3(1) - CI*P3(2)) + V1(6)*(P3(0) + P3(3)))
      TMP3 = (V1(3)*(P2(0) - P2(3)) - V1(4)*(P2(1) + CI*P2(2)) - V1(5)*(P2(1) - CI*P2(2)) + V1(6)*(P2(0) + P2(3)))
      V2(3) = DENOM*CI*((TMP0 - TMP1)*V1(3) + (TMP2 - TMP3)*V3(3))/2
      V2(4) = DENOM*CI*((TMP0 - TMP1)*V1(4) + (TMP2 - TMP3)*V3(4))/2
      V2(5) = DENOM*CI*((TMP0 - TMP1)*V1(5) + (TMP2 - TMP3)*V3(5))/2
      V2(6) = DENOM*CI*((TMP0 - TMP1)*V1(6) + (TMP2 - TMP3)*V3(6))/2
      END


