C     This file was automatically generated by ALOHA
C     but has been modified by CAFE

      SUBROUTINE VVIVLVL1P0_3(V1, V2, V4, COUP, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M3
      REAL*8 P3(0:3)
      COMPLEX*16 TMP1
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(6)
      COMPLEX*16 V4(*)
      REAL*8 W3
      COMPLEX*16 DENOM
      V3(1) = +V1(1)+V2(1)+V4(1)
      V3(2) = +V1(2)+V2(2)+V4(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      TMP1 = V1(3)*V4(6) - V1(4)*V4(5) - V1(5)*V4(4) + V1(6)*V4(3)
      V3(3) = -DENOM*CI*(TMP1*V2(3))/2
      V3(4) = -DENOM*CI*(TMP1*V2(4))/2
      V3(5) = -DENOM*CI*(TMP1*V2(5))/2
      V3(6) = -DENOM*CI*(TMP1*V2(6))/2
      END


