      SUBROUTINE LRV1_0(F1,LENGTHF1,PF1,MOF1,F2,LENGTHF2,PF2,MOF2,V3,PV3,V3L,V3R,NEXTERNAL,
     & MSQR,MANG,COUP,VERTEX)      
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      DOUBLE PRECISION RTWO
      PARAMETER (RTWO=2.0D0)
      INTEGER I,J,LENGTHF1,LENGTHF2
      INTEGER NEXTERNAL,V3L,V3R
      INTEGER MOF1(*),MOF2(*)
      COMPLEX*16, DIMENSION(NEXTERNAL,NEXTERNAL) :: MSQR
      COMPLEX*16, DIMENSION(NEXTERNAL,NEXTERNAL) :: MANG
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 PF1(*)
      COMPLEX*16 PF2(*)
      COMPLEX*16 PV3(*)
      COMPLEX*16 INPRODLMO1F1V3R
      COMPLEX*16 INPRODLMO2F1V3R
      COMPLEX*16 INPRODRV3F2
      COMPLEX*16 POLPRUDLV3V3R
      COMPLEX*16 SUMF1
      COMPLEX*16 SUMF2
      COMPLEX*16 VERTEX
      
      SUMF1 = 0
      SUMF2 = 0
      
      IF (LENGTHF1.GT.0) THEN
        DO I = 1, LENGTHF1
          SUMF1 = SUMF1 + F1(I)*MSQR(ABS(MOF1(I)),ABS(V3L))
        ENDDO
      ELSE
        SUMF1 = MSQR(ABS(MOF1(1)),V3L)
      ENDIF
      
      IF (LENGTHF2.GT.0) THEN
        DO J = 1, LENGTHF2
          SUMF2 = SUMF2 + F2(J)*MANG(ABS(V3R),ABS(MOF2(J)))
        ENDDO
      ELSE
        SUMF2 = MANG(ABS(V3R),ABS(MOF2(1)))       
      ENDIF
        
      VERTEX = -COUP * (DSQRT(RTWO)/PV3(3)) * SUMF1 * SUMF2 
      END
