C     This file was automatically generated by ALOHA
C     but has been modified by CAFE

      SUBROUTINE RRV1_1(F2,LEF2,PF2,MOF2,V3,PV3,MO3L,MO3R,NEXTERNAL,
     & MSQR,MANG,COUP,M1,W1,MOF1,F1,PF1,LEF1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      DOUBLE PRECISION RTWO
      PARAMETER (RTWO=2.0D0)
      INTEGER NEXTERNAL,I,J
C     EB: Length of F1 and F2.
      INTEGER LEF1,LEF2
C     EB: Left external mothers of F1 and F2.
      INTEGER MOF1(*),MOF2(*)
C     EB: Left and right external mothers of V3.
      INTEGER MO3L(*),MO3R(*)
      COMPLEX*16 COUP
C     EB: Vectors carrying innerproducts from previous vertices
C         for the fermions and the boson.
      COMPLEX*16 F1(*),F2(*),V3(*)
C     EB: Complex, 2-component version of 
C         momentum of F1, F2, and V3.
C     EB: PV3(3) gives the innerproduct 
C         for the polarisation factor of V3. 
      COMPLEX*16 PF1(*),PF2(*),PV3(*)
C     EB: Real version of F1 momentum.
      REAL*8 P1(0:3)
C     EB: Matrices containing all innerproducts for the process.
C         MSQR contains the square innerproducts.
C         MANG contains the angle innerproducts.
      COMPLEX*16, DIMENSION(NEXTERNAL,NEXTERNAL) :: MSQR
      COMPLEX*16, DIMENSION(NEXTERNAL,NEXTERNAL) :: MANG
      REAL*8 M1
      REAL*8 W1
      COMPLEX*16 DENOM
      COMPLEX*16 SUMF2
      
      PF1(1) = +PF2(1)+PV3(1)
      PF1(2) = +PF2(2)+PV3(2)
      P1(0) = -DBLE(PF1(1))
      P1(1) = -DBLE(PF1(2))
      P1(2) = -DIMAG(PF1(2))
      P1(3) = -DIMAG(PF1(1))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2)
      SUMF2 = 0
      
C     EB: if F2 is internal.
      IF (LEF2.GT.0) THEN
        LEF1=LEF2+1
        DO I = 1,LEF2
          SUMF2 = SUMF2 + F2(I)*MANG(ABS(MOF1(I)),ABS(MO3R(1)))
        ENDDO
C     EB: else F2 is external.
      ELSE
        LEF1=LEF2+2
        SUMF2 = MANG(ABS(MOF2(1)),ABS(MO3R(1)))
      ENDIF
      
      DO J = 1, LEF1
C       EB: if external mother of F1 is final. 
        IF (MOF1(J).GT.0) THEN
         F1(J) = -DENOM*CI*(DSQRT(RTWO)/PV3(3))*SUMF2*MSQR(ABS(MO3L(1)),ABS(MOF1(J)))
        ENDIF
C       EB: if external mother of F1 is initial. 
        IF (MOF1(J).LT.0) THEN
         F1(J) = DENOM*CI*(DSQRT(RTWO)/PV3(3))*SUMF2*MSQR(ABS(MO3L(1)),ABS(MOF1(J)))
        ENDIF 
      ENDDO 
      END
